variables:
- name: ModuleName
  value: CATEncryptor
- group: PSGalleryKey

trigger:
- main

jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: windows-latest
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/build.ps1'
    - task: PowerShell@2
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        failOnStderr: true
        pwsh: true
        targetType: 'inline'
        script: |
          Publish-Module -Path ".\out\$(ModuleName)" -NugetAPIKey "$(ApiKey)"
      displayName: Publish Module
      name: publishModule
